# Generated by Django 5.1.1 on 2024-12-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentimentAnalysiss',
            new_name='SentimentAnalysis',
        ),
    ]
