# Generated by Django 5.1.1 on 2024-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_rename_sentimentanalysiss_sentimentanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalysis',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
